{% set name = "omero-py" %}
{% set version = "5.6.dev4" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}{{ environ.get('VERSION_SUFFIX', '') }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0584ce6bfe069782a7ec51b87392c96b9005bf64130a2dee022f063dcb2c9491

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "
  script_env:
    - VERSION_SUFFIX

requirements:
  host:
    - pip
    - python =3
  run:
    - future
    - python =3
    - zeroc-ice36-python

test:
  commands:
    - omero --help
    - omero version
  imports:
    - omero
    - omero.api
    - omero.clients
    - omero.cmd
    - omero.constants
    - omero.fs
    - omero.gateway
    - omero.grid
    - omero.install
    - omero.metadatastore
    - omero.model
    - omero.plugins
    - omero.romio
    - omero.sys
    - omero.util
    - omero_ext

about:
  home: https://www.openmicroscopy.org/
  license: GNU General Public v2 or later (GPLv2+)
  license_family: GPL2
  summary: Python bindings to the OMERO.blitz server
  doc_url: https://docs.openmicroscopy.org/latest/omero/developers
  dev_url: https://github.com/ome/omero-py

extra:
  recipe-maintainers:
    - ome
